import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="text-center py-6">
          <h1 className="text-3xl font-bold text-gray-800">父レコ</h1>
        </header>

        <main className="flex justify-center">
          <div className="bg-white rounded-lg shadow-md p-6 w-full max-w-xl">
            {children}
          </div>
        </main>

        <footer className="fixed bottom-4 w-full flex justify-center">
          <div className="text-gray-500">📱 👨‍👩‍👧‍👦 🩺</div>
        </footer>

      
      </body>
    </html>
  );
}
